import Foundation
import ReclyCore
import Security

/// docs/05 "secrets": the name is the only part of a secret that ever leaves this device — it is what
/// a step's `secretRef` holds — so it obeys the same `^[a-z][a-z0-9_]{0,31}$` the parser enforces on
/// `secretRef` (docs/02). A name this rejects could be stored but never referenced.
public enum SecretName {
    public static let rule = "^[a-z][a-z0-9_]{0,31}$"

    /// Nil when the name is usable, otherwise why it is not — as a key rather than a sentence
    /// (docs/07 rule 3), because the complaint stays on the form for as long as the name does and
    /// has to answer a language change made while it is standing.
    public static func problem(_ name: String, existing: [String] = []) -> UiMessage? {
        if name.isEmpty { return .key("Enter a name") }
        if name.range(of: rule, options: .regularExpression) == nil {
            return .key("Starts with a lowercase letter; lowercase, digits and underscores, up to 32")
        }
        if existing.contains(name) { return .key("That name already exists") }
        return nil
    }
}

/// `SecretsRepository` as [SecretStore] uses it. A protocol only so that a store which refuses —
/// a locked Keychain, a missing entitlement — is a case a test can produce; `CoreSecrets` is the
/// one conformance the apps ever see.
protocol Secrets {
    func names() async throws -> [String]

    func put(name: String, value: String) async throws

    func delete(name: String) async throws
}

/// The core's repository, as the protocol above spells it.
struct CoreSecrets: Secrets {
    let repository: SecretsRepository

    func names() async throws -> [String] {
        try await repository.names()
    }

    func put(name: String, value: String) async throws {
        try await repository.put(name: name, value: value)
    }

    func delete(name: String) async throws {
        try await repository.delete(name: name)
    }
}

/// The `secrets` namespace of the device's Keychain, as the editor sees it (docs/05: names travel
/// in `workflows.json`, values never leave this device).
///
/// Every read and write goes through the core's `SecretsRepository` rather than straight at the
/// Keychain: docs/05 "코어 구현 메모" makes that the one entry point the core owns.
///
/// The listing is still the store's own — the phone's `SecretStore` makes the same argument: a name
/// index kept alongside is a second source of truth that a restore or a crash between two writes
/// can silently desynchronise, and a `secretRef` pointing at a name the store does not really have
/// is exactly the failure the "no key on this device" badge exists to prevent.
public struct SecretStore {
    private let secrets: Secrets

    public init(secrets: SecretsRepository) {
        self.secrets = CoreSecrets(repository: secrets)
    }

    /// The seam a test refuses a write through; the shells only ever get the initializer above.
    init(secrets: Secrets) {
        self.secrets = secrets
    }

    public func names() async throws -> [String] {
        try await secrets.names()
    }

    public func put(name: String, value: String) async throws {
        try await secrets.put(name: name, value: value)
    }

    public func delete(name: String) async throws {
        try await secrets.delete(name: name)
    }

    /// docs/04's `whsec_…`, generated by the core so every platform's secrets are the same shape.
    public func generate() -> String {
        Signer.shared.generateSecret(random: SecureRandom())
    }
}

/// `Random.Default` is not a cryptographic generator and this is a signing key, so the one method
/// Kotlin's `Random` builds everything else out of is answered by `SecRandomCopyBytes` (the phone
/// does the same with `SecureRandom().asKotlinRandom()`).
final class SecureRandom: KotlinRandom {
    override func nextBits(bitCount: Int32) -> Int32 {
        guard bitCount > 0 else { return 0 }
        var word: UInt32 = 0
        let status = withUnsafeMutableBytes(of: &word) {
            SecRandomCopyBytes(kSecRandomDefault, $0.count, $0.baseAddress!)
        }
        // `SecRandomCopyBytes` fails only when the system's generator is unavailable, which is not
        // a state a webhook secret may be minted in.
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed: \(status)")
        // Kotlin's contract: the low [bitCount] bits are the random ones.
        return Int32(bitPattern: word >> (32 - UInt32(bitCount)))
    }
}
