import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
}

/**
 * docs/06: the Windows client is a **Desktop** OAuth client, whose `client_secret` Google's own
 * documentation says is not a secret — but it is per-developer, so it is never committed (README).
 * Order: `local.properties`, then the environment, then a placeholder that keeps the build green
 * and only makes sign-in fail (the phone does the same, `android/app/build.gradle.kts`).
 */
val localProperties: Properties = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}

fun oauth(key: String, env: String, fallback: String): String =
    localProperties.getProperty(key) ?: System.getenv(env) ?: fallback

version = "0.0.1-dev"

/**
 * `BuildConfig` by hand: one generated object, so the ids are compiled in rather than read off a
 * file the packaged app would have to carry.
 */
val generateOAuthConfig = tasks.register("generateOAuthConfig") {
    val clientId = oauth("google.desktopClientId", "REC_GOOGLE_DESKTOP_CLIENT_ID", "REPLACE_ME.apps.googleusercontent.com")
    val clientSecret = oauth("google.desktopClientSecret", "REC_GOOGLE_DESKTOP_CLIENT_SECRET", "REPLACE_ME")
    val version = project.version.toString()
    val output = layout.buildDirectory.dir("generated/oauth")
    inputs.property("clientId", clientId)
    inputs.property("clientSecret", clientSecret)
    inputs.property("version", version)
    outputs.dir(output)
    doLast {
        val file = output.get().file("app/recly/windows/auth/OAuthConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by :windows:app:generateOAuthConfig — do not edit.
            package app.recly.windows.auth

            object OAuthConfig {
                const val CLIENT_ID: String = "$clientId"
                const val CLIENT_SECRET: String = "$clientSecret"
                const val APP_VERSION: String = "$version"

                /** True while the placeholders are in place: sign-in is offered but cannot work. */
                val isPlaceholder: Boolean get() = CLIENT_ID.startsWith("REPLACE_ME")
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(21)
    sourceSets.main { kotlin.srcDir(generateOAuthConfig) }
}

dependencies {
    implementation(project(":core"))

    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    // Dispatchers.Main on the JVM: the AWT file dialogs (workflow export/import) hop to it, and
    // nothing else on the runtime classpath provides a Main dispatcher.
    implementation(libs.kotlinx.coroutines.swing)

    // The JDBC driver is `implementation` in :core, so the shell that opens the file needs its own.
    implementation(libs.sqldelight.sqlite.driver)
    // docs/06 Windows: the loopback redirect receiver.
    implementation(libs.ktor.server.cio)
    // Credential Manager and the HKCU Run key (docs/14 "앱"). Windows-only at runtime; on macOS
    // nothing reaches them (see `SecureStores`, `LaunchAtLogin`).
    implementation(libs.jna)
    implementation(libs.jna.platform)

    testImplementation(kotlin("test"))
    testImplementation(libs.kotlinx.coroutines.test)
}

tasks.test {
    useJUnitPlatform()
    // M6-L2: forwarded to the test JVM so the protocol tests can be pointed at the real Rust capture
    // helper instead of `dev/FakeHelper.java` (see `FakeHelperCommand`). Gradle's `-D` reaches the
    // daemon, not the workers.
    System.getProperty("recly.captureHelper")?.let { systemProperty("recly.captureHelper", it) }
    // The same forwarding for the docs/20 acceptance harness (`acceptance/DesktopAcceptance.kt`),
    // which is skipped unless `recly.acceptance=1` reaches the worker.
    listOf(
        "recly.acceptance",
        "recly.acceptance.dataDir",
        "recly.acceptance.authUrlFile",
        "recly.acceptance.authTimeoutSec",
        "recly.acceptance.webhookSecret",
        "recly.acceptance.webhookUrl",
        "recly.acceptance.removeStaleNamed",
    ).forEach { key -> System.getProperty(key)?.let { systemProperty(key, it) } }
}

compose.desktop {
    application {
        mainClass = "app.recly.windows.MainKt"

        nativeDistributions {
            /**
             * docs/14 "앱": the MSI carries the capture helper and — ADR-019 — an LGPL ffmpeg next
             * to it. jpackage copies the platform's subdirectory into the installed app and hands
             * the app its path in `compose.application.resources.dir`, which is where
             * `CaptureHelper.command()` looks. `.github/workflows/windows.yml` is what puts the two
             * binaries in `resources/windows-x64` before `packageMsi`; the directory is otherwise
             * empty in git (`windows/README.md`).
             */
            appResourcesRootDir.set(project.layout.projectDirectory.dir("resources"))

            // MSI is the Windows target (docs/14 N7); the DMG is what this development machine can
            // actually build and is how `packageDistributionForCurrentOS` is verified here.
            targetFormats(TargetFormat.Msi, TargetFormat.Dmg)

            // jpackage ships a runtime with only the modules named here, and a missing one is a
            // crash at startup rather than a build error. `java.sql` is SQLDelight's JDBC driver
            // (found the hard way: the packaged app died on `java.sql.DriverManager`); `java.naming`
            // and `jdk.crypto.ec` are what TLS needs for Drive; `jdk.unsupported` is JNA's.
            modules("java.sql", "java.naming", "jdk.crypto.ec", "jdk.unsupported")
            packageName = "Recly"
            packageVersion = version.toString().substringBefore('-') // MSI wants MAJOR.MINOR.BUILD
            vendor = "Recly"
            description = "Recly — record and run workflows"

            // docs/09 "앱 아이콘": one master, per-platform exports. jpackage wants a different
            // container per platform, and all three are written by `scripts/render-icons.swift`.
            val icons = project.layout.projectDirectory.dir("src/main/icons")

            windows {
                iconFile.set(icons.file("recly.ico"))
                menu = true
                menuGroup = "Recly"
                // A desktop shortcut, and a chance to say where it goes: this is a tray app, and an
                // install with no icon anywhere is one nobody finds again.
                shortcut = true
                dirChooser = true
                // `%LOCALAPPDATA%` is where the data lives (`Host.dataDir`) and HKCU is where the
                // Run key does (`WindowsRunKey`): a per-user install needs no elevation and matches
                // both. docs/14 "앱": launch at login stays the app's own setting — an MSI cannot
                // write a Run key that the user can then turn off from the tray.
                perUserInstall = true
                // Stable across releases so an upgrade replaces the install rather than adding one.
                upgradeUuid = "6f3a1f2e-9b64-4a4e-9f0d-2a0c9a1d5b71"
            }
            linux {
                iconFile.set(icons.file("recly.png"))
            }
            macOS {
                iconFile.set(icons.file("recly.icns"))
                bundleID = "app.recly.windows"
                // macOS refuses a major version of 0, and this bundle is only ever the development
                // host's build of a Windows app (M6-L1 "환경 제약") — the shipped version is the
                // project's, which is what `OAuthConfig.APP_VERSION` and the MSI carry.
                packageVersion = "1.0.0"
            }
        }
    }
}
